### PR TITLE
Remove side effect from `json`

### PR DESCRIPTION
**Pull request by timneutkens**
I don't think it is wrong to parse the json twice in this case. Maybe we could cache the json parse in some other way. At least the log function should be independent from the json parsing.

@rauchg could you take a look at this?

### CODE REVIEW

**Comment by rauchg** [comment]
100% agree that during dev double parsing should totally be fine

**Comment by rickharrison** [comment]
I was under the impression that double parsing didn't work which is why I did it that way. I'll have to test.

**Comment by timneutkens** [comment]
@rickharrison fair point, just tested it. The `req` srteam gets ended by `raw-body`. So the second time you call it, it will hang. `body-parser` handles it kind of the same way you did:
https://github.com/expressjs/body-parser/blob/bb546ef9b9c51bb33ad72f5e5300e12296bb26d7/lib/read.js#L44
https://github.com/expressjs/body-parser/blob/bb546ef9b9c51bb33ad72f5e5300e12296bb26d7/lib/types/json.js#L92
https://github.com/expressjs/body-parser/blob/bb546ef9b9c51bb33ad72f5e5300e12296bb26d7/lib/read.js#L116

@rickharrison @rauchg maybe we should implement the same behaviour 🤔

**Comment by timneutkens** [comment]
@rickharrison @rauchg So what I did is store the promise in `req.rawBody` which is always executed only once. I don't like modifying `req` too, but in this case, as @rickharrison said, it is a necessary evil.

**Comment by rickharrison** [comment]
Just cherry picked the commits over and added a section to the readme! https://github.com/zeit/micro/pull/104

**Pull request closed without merging**
